version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
