tags:
  - name: admin
    description: Admin API
  - name: weather
    description: Weather API

paths:
  /api/v1/weather:
    get:
      tags:
        - weather
      summary: Get weather by address
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/street'
        - $ref: '#/components/parameters/streetNumber'
        - $ref: '#/components/parameters/town'
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/postalCode'
      responses:
        200:
          description: 'OK'
        404:
          description: 'Not valid'
        500:
          description: 'Server Error'
  /api/v1/weather/address/validate:
    get:
      tags:
        - weather
      summary: Validates address
      parameters:
        - $ref: '#/components/parameters/street'
        - $ref: '#/components/parameters/streetNumber'
        - $ref: '#/components/parameters/town'
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/postalCode'
      responses:
        200:
          description: 'OK'
        404:
          description: 'Not valid'
        500:
          description: 'Server Error'

  /admin/users:
    get:
      tags:
        - admin
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    post:
      tags:
        - admin
      summary: Add User
      parameters:
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        404:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /admin/users/{id}:
    get:
      tags:
        - admin
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
      responses:
        200:
          description: 'OK'
        404:
          description: 'Not Found'
        500:
          description: 'Server Error'

    put:
      tags:
        - admin
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        404:
          description: 'Not Found'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    delete:
      tags:
        - admin
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
      responses:
        200:
          description: 'OK'
        404:
          description: 'Not Found'
        500:
          description: 'Server Error'

definitions:
  users:
    type: object
    required:
      - email
      - password
    properties:
      id:
        description: user Id
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    street:    
      in: query
      name: street
      required: true
      schema:
        type: string 
    streetNumber:
      in: query
      name: streetNumber
      required: true
      schema:
        type: string   
    town:
      in: query
      name: town
      required: true
      schema:
        type: string  
    country:
      in: query
      name: country
      required: true
      schema:
        type: string  
    postalCode:
      in: query
      name: postalCode
      required: true
      schema:
        type: string

schemes:
 - https
 - http
